name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          echo "Django<4.0" >> dev-requirements.txt
          pip install -r dev-requirements.txt

      - name: Run flake8
        run: flake8 sendgrid_backend/

      - name: Check import order with isort
        run: isort -c ./

      - name: Check code style with black
        run: black --check ./

      - name: Type check with mypy
        run: mypy sendgrid_backend/

      - name: Run tests with tox
        env:
          TOXENV: py38
        run: tox
