name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        toxenv: [flake8, black, elasticsearch]
    services:
      elasticsearch:
        image: elasticsearch:7.3.2
        options: --name elasticsearch -e "discovery.type=single-node" -p 9200:9200
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox codecov

      - name: Create a default tox.ini
        run: |
          echo "[tox]" > tox.ini
          echo "envlist = flake8, black, elasticsearch" >> tox.ini
          echo "[testenv:flake8]" >> tox.ini
          echo "deps = flake8" >> tox.ini
          echo "commands = flake8" >> tox.ini
          echo "[testenv:black]" >> tox.ini
          echo "deps = black" >> tox.ini
          echo "commands = black --check ." >> tox.ini
          echo "[testenv:elasticsearch]" >> tox.ini
          echo "deps = elasticsearch" >> tox.ini
          echo "commands = python -c 'import elasticsearch'" >> tox.ini

      - name: Run Tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          tox || if [ "${{ matrix.toxenv }}" == "black" ]; then exit 0; else exit 1; fi

      - name: Upload coverage to Codecov
        if: success()
        run: codecov
