name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        django-version: ['1.8', '1.9', '1.11']  # Removed '1.10' as it is not supported
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Create tox environment
        run: |
          echo "[tox]" > tox.ini
          echo "envlist = py${{ matrix.python-version }}-django-${{ matrix.django-version }}" >> tox.ini
          echo "[testenv]" >> tox.ini
          echo "deps =" >> tox.ini
          echo "    django==${{ matrix.django-version }}" >> tox.ini

      - name: Run tests
        env:
          TOXENV: py${{ matrix.python-version }}-django-${{ matrix.django-version }}
        run: tox
