name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'

      - name: Ensure script permissions
        run: chmod +x scripts/link-format-chk.sh scripts/buildtable.pl

      - name: Run link format check
        run: scripts/link-format-chk.sh

      - name: Build table
        run: |
          scripts/buildtable.pl >/tmp/table.mediawiki || exit 1
          diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' >/tmp/after.diff || true

      - name: Compare with previous commit
        run: |
          if git checkout HEAD^ && scripts/buildtable.pl >/tmp/table.mediawiki 2>/dev/null; then
            diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' >/tmp/before.diff || true
            newdiff=$(diff -s /tmp/before.diff /tmp/after.diff -u | grep '^+')
            if [ -n "$newdiff" ]; then
              echo "$newdiff"
              exit 1
            fi
          else
            echo 'Cannot build previous commit table for comparison'
          fi
