name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        toxenv:
          - py38

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make install script executable
        run: chmod +x ./.travis/install

      - name: Make run script executable
        run: chmod +x ./.travis/run

      - name: Install dependencies
        run: ./.travis/install

      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: ./.travis/run tox

  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Make install script executable
        run: chmod +x ./.travis/install

      - name: Install dependencies
        run: ./.travis/install

      - name: Run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls
